### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot parse iv:ciphertext:mac

### ISSUE THREAD

**Issue by yekmer** [orhanobut/hawk#106]
I am using version 1.17,

We are getting this error on some of the devices, (HUAWEI Y300-0100, VS930 4G, GT-18552, LG-F100L). Affected operating systems are(Android 4.1.1 and 4.1.2). Locale is all "en". This is our full error stacktrace

at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4247)
at android.app.ActivityThread.access$1300(ActivityThread.java:137)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1270)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)  
at android.app.ActivityThread.main(ActivityThread.java:4838)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:875)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:642)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalArgumentException: Cannot parse iv:ciphertext:mac
at com.orhanobut.hawk.AesCbcWithIntegrity$CipherTextIvMac.<init>(AesCbcWithIntegrity.java:538)
at com.orhanobut.hawk.AesEncryption.getCipherTextIvMac(AesEncryption.java:77)
at com.orhanobut.hawk.AesEncryption.decrypt(AesEncryption.java:62)
at com.orhanobut.hawk.Hawk.get(Hawk.java:132)

Thanks

**Comment by JohnFrontzos** [comment]
I am also experience the same issue.
**Device**: Android Nexus 5
**Android** version: 6.0
**Hawk Lib** version: 1.20

But in Genymotion nexus 5, 5.1.0 image is working!
```
 Caused by: java.lang.IllegalArgumentException: Cannot parse iv:ciphertext:mac
 at com.orhanobut.hawk.AesCbcWithIntegrity$CipherTextIvMac.<init>(AesCbcWithIntegrity.java:545)
at com.orhanobut.hawk.AesEncryption.getCipherTextIvMac(AesEncryption.java:75)
at com.orhanobut.hawk.AesEncryption.decrypt(AesEncryption.java:60)
at com.orhanobut.hawk.Hawk.get(Hawk.java:125)
```

**Comment by orhanobut** [comment]
I've added this to in my backlog as well, I'll check it as soon as possible.

**Comment by chuross** [comment]
I got this problem from the error report.

Hawk lib version: 1.18
Device: FJL21(OS 4.1.2), SHL21(OS 4.1.2), HTX21(4.0.4)

```
Caused by java.lang.IllegalArgumentException: Cannot parse iv:ciphertext:mac
       at com.orhanobut.hawk.AesCbcWithIntegrity$CipherTextIvMac.(AesCbcWithIntegrity.java:538)
       at com.orhanobut.hawk.AesEncryption.getCipherTextIvMac(AesEncryption.java:3077)
       at com.orhanobut.hawk.Hawk.get(Hawk.java:128)
```

**Comment by JerzyPuchalski** [comment]
Problem is still occurring with 1.21. My device is Nexus 6P. Switching SharedPreferences storage to SQLite DB solved the issue.

**Comment by PieterAelse** [comment]
@orhanobut any updates on this one? Also experiencing this in production on Samsung GT-I8730 (Android 4.1.2)

**Comment by novalu** [comment]
Same problem in production for several users with Hawk 1.22. Any updates? Thank you.

HUAWEI U8815, Android 4.0.3
LG-P760, Android 4.1.2
G526-L11, Android 4.1.2
LT28h, Android 4.1.2

**Comment by kibotu** [comment]
```
    java.lang.IllegalArgumentException: Cannot parse iv:ciphertext:mac
    at com.orhanobut.hawk.AesCbcWithIntegrity$CipherTextIvMac.<init>(AesCbcWithIntegrity.java:545)
    at com.orhanobut.hawk.AesEncryption.getCipherTextIvMac(AesEncryption.java:71)
    at com.orhanobut.hawk.AesEncryption.decrypt(AesEncryption.java:57)
    at com.orhanobut.hawk.Hawk.get(Hawk.java:123)
```
Using medium encryption.

```
Hawk.init(getContext())
                .setEncryptionMethod(HawkBuilder.EncryptionMethod.MEDIUM)
                .setStorage(HawkBuilder.newSharedPrefStorage(getContext()))
                .build();
```

Happens on Samsung SG7 6.01, too sadly :(

**Comment by orhanobut** [comment]
I'm working on update for the missing crypto packages, hopefully I'll get rid of all dependencies from the  Android version (custom rom) etc.

**Comment by PieterAelse** [comment]
Any updates?

**Comment by Shafichariri** [comment]
I am getting the same problem on 4.1.2 ... 
Any updates? Is there any work around?
Thanks

**Comment by astuetz** [comment]
+1

**Comment by isiyin** [comment]
I've got the same problem reported by several users while using Hawk 1.23.
[ android 4.1.2 (16)，samsung:GT-N7100:armeabi-v7a]
Hope you can fix this bug soon.
Thanks.

**Comment by orhanobut** [comment]
Unfortunately I can't solve this problem easily and I no longer support Hawk v1. I switched Hawk to conceal. Hawk 2.0 should not have any of this problems

**Comment by orhanobut** [comment]
Closing this one.
