### ISSUE TITLE
hawk.HawkBuilder.getStorage()' on a null object reference

### ISSUE THREAD

**Issue by coffeearmy** [orhanobut/hawk#107]
Hi!
I'm using v 1.20, and I got this exception:

 java.lang.RuntimeException: Unable to start activity  **
java.lang.NullPointerException: Attempt to invoke virtual method 'com.orhanobut.hawk.Storage com.orhanobut.hawk.HawkBuilder.getStorage()' on a null object reference
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
            at android.app.ActivityThread.-wrap11(ActivityThread.java)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

This exceptions appears every time one of my activities closes, but the app continues working, when the app try to get a value with Hawk.get.
The problem is in Hawk.class line 89 : "String fullText = (String)hawkBuilder.getStorage().get(key);" hawkBuilder is null.

Thanks!

**Comment by orhanobut** [comment]
Hi, I'll check it very soon. Currently a little busy that cannot check, sorry for that.

**Comment by never615** [comment]
interim programme...
```
BaseActivity{

@Override
protected void onResume() {
   super.onResume();

   Hawk.init(this)
           .setEncryptionMethod(HawkBuilder.EncryptionMethod.NO_ENCRYPTION)
           .setStorage(HawkBuilder.newSharedPrefStorage(this))
           .build();

}
```

**Comment by orhanobut** [comment]
This shouldn't be an issue with the new version. Closing this one.
