### ISSUE TITLE
Hawk stackoverflow error

### ISSUE THREAD

**Issue by imdatcandan** [orhanobut/hawk#115]
Hi Orhan Abi,
When I try the code below, I got the stackoverflow error, do you have any idea how can I solve it? It comes to me weird since I didn't face this problem on Hawk before.

I initialized the Hawk in application class.
 Hawk.init(this)
                .setEncryptionMethod(HawkBuilder.EncryptionMethod.NO_ENCRYPTION)
                .setStorage(HawkBuilder.newSqliteStorage(this))
                .build();

I put the list to Hawk in Activity class.
  categoryItemList = new ArrayList<CategoryItem>();
  categoryItemList.add(new CategoryItem(title, text));
  Hawk.put("categoryItemList", categoryItemList);

12-01 21:17:00.503 17521-17521/? E/dalvikvm: Could not find class 'com.orhanobut.hawk.Hawk$2', referenced from method com.orhanobut.hawk.Hawk.getObservable
12-01 21:17:00.504 17521-17521/? E/dalvikvm: Could not find class 'com.orhanobut.hawk.Hawk$1', referenced from method com.orhanobut.hawk.Hawk.putObservable
12-01 21:17:00.507 17521-17521/? E/dalvikvm: Could not find class 'com.orhanobut.hawk.HawkBuilder$2', referenced from method com.orhanobut.hawk.HawkBuilder.buildRx
FATAL EXCEPTION: main
        Process: com.simplitute.copycatt, PID: 16543
        java.lang.StackOverflowError
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:381)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:376)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:381)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:376)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:381)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:376)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:381)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:376)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:381)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:376)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:381)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:376)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:381)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:376)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:381)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:376)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:381)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:376)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:381)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:376)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:381)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:376)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:381)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:376)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:381)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:376)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:381)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:376)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:381)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:376)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:381)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:376)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:381)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:376)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:381)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:376)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:381)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:356)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:141)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:83)
        at com.google.gson.Gson.getAdapter(Gson.java:359)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(ReflectiveTypeAdapterFactory.java:122)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.access$100(ReflectiveTypeAdapterFactory.java:46)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:92)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:91)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:142)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:83)
        at com.google.gson.Gson.getAdapter(Gson.java:359)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(ReflectiveTypeAdapterFactory.java:122)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.access$100(ReflectiveTypeAdapterFactory.java:46)
        at com.google.gson.inter

**Comment by orhanobut** [comment]
let me check @imdatcandan

**Comment by imdatcandan** [comment]
After new release, I didn't face this problem

**Comment by orhanobut** [comment]
Great!

**Comment by KaneLkh** [comment]
Hello,I meet this question! Ihave try this way! but no use!

08-04 16:26:51.600 19062-19062/com.xymens.app E/dalvikvm: Could not find class 'com.orhanobut.hawk.Hawk$2', referenced from method com.orhanobut.hawk.Hawk.getObservable
08-04 16:26:51.600 19062-19062/com.xymens.app W/dalvikvm: VFY: unable to resolve new-instance 4830 (Lcom/orhanobut/hawk/Hawk$2;) in Lcom/orhanobut/hawk/Hawk;
08-04 16:26:51.600 19062-19062/com.xymens.app D/dalvikvm: VFY: replacing opcode 0x22 at 0x0003
08-04 16:26:51.600 19062-19062/com.xymens.app I/dalvikvm: Failed resolving Lcom/orhanobut/hawk/Hawk$1; interface 8561 'Lrx/Observable$OnSubscribe;'
08-04 16:26:51.600 19062-19062/com.xymens.app W/dalvikvm: Link of class 'Lcom/orhanobut/hawk/Hawk$1;' failed
08-04 16:26:51.600 19062-19062/com.xymens.app E/dalvikvm: Could not find class 'com.orhanobut.hawk.Hawk$1', referenced from method com.orhanobut.hawk.Hawk.putObservable
08-04 16:26:51.600 19062-19062/com.xymens.app W/dalvikvm: VFY: unable to resolve new-instance 4829 (Lcom/orhanobut/hawk/Hawk$1;) in Lcom/orhanobut/hawk/Hawk;
08-04 16:26:51.600 19062-19062/com.xymens.app D/dalvikvm: VFY: replacing opcode 0x22 at 0x0003
08-04 16:26:51.605 19062-19062/com.xymens.app I/dalvikvm: Failed resolving Lcom/orhanobut/hawk/Hawk$2; interface 8561 'Lrx/Observable$OnSubscribe;'
08-04 16:26:51.605 19062-19062/com.xymens.app W/dalvikvm: Link of class 'Lcom/orhanobut/hawk/Hawk$2;' failed
08-04 16:26:51.605 19062-19062/com.xymens.app D/dalvikvm: DexOpt: unable to opt direct call 0x8c30 at 0x05 in Lcom/orhanobut/hawk/Hawk;.getObservable
08-04 16:26:51.605 19062-19062/com.xymens.app I/dalvikvm: Failed resolving Lcom/orhanobut/hawk/Hawk$1; interface 8561 'Lrx/Observable$OnSubscribe;'
08-04 16:26:51.605 19062-19062/com.xymens.app W/dalvikvm: Link of class 'Lcom/orhanobut/hawk/Hawk$1;' failed
08-04 16:26:51.605 19062-19062/com.xymens.app D/dalvikvm: DexOpt: unable to opt direct call 0x8c2d at 0x05 in Lcom/orhanobut/hawk/Hawk;.putObservable
08-04 16:26:51.605 19062-19062/com.xymens.app I/dalvikvm: Failed resolving Lcom/orhanobut/hawk/HawkBuilder$2; interface 8564 'Lrx/functions/Func0;'
08-04 16:26:51.605 19062-19062/com.xymens.app W/dalvikvm: Link of class 'Lcom/orhanobut/hawk/HawkBuilder$2;' failed
08-04 16:26:51.605 19062-19062/com.xymens.app E/dalvikvm: Could not find class 'com.orhanobut.hawk.HawkBuilder$2', referenced from method com.orhanobut.hawk.HawkBuilder.buildRx
08-04 16:26:51.605 19062-19062/com.xymens.app W/dalvikvm: VFY: unable to resolve new-instance 4835 (Lcom/orhanobut/hawk/HawkBuilder$2;) in Lcom/orhanobut/hawk/HawkBuilder;

**Comment by KaneLkh** [comment]
this is hawk init.
        Hawk.init(application)
                .setEncryptionMethod(HawkBuilder.EncryptionMethod.NO_ENCRYPTION)
                .build();
