### ISSUE TITLE
IllegalStateException: Cannot perform this operation because the connection pool has been closed.

### ISSUE THREAD

**Issue by PieterAelse** [orhanobut/hawk#118]
I'm using Hawk with SQL Storage and EncryptionMethod.HIGHEST in my Widget. So that's in the AppWidgetProvider (which basically is a BroadcastReceiver), a RemoteViewsService (which is a Service) and some Activities. I'm getting this IllegalStateException sometimes after/with heavy usage. So I thought it was some multi-threading issue and made sure all my methods which use Hawk are synchronized, but this didn't fix the issue (which crashes my widget/app). 
And try/catching every .get() I do on Hawk doesn't look like a good way forward. 

So could you check this bug?

```E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                java.lang.RuntimeException: Unable to start receiver com.example.widget.MyAppWidgetProvider: java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
                                                                                    at android.app.ActivityThread.handleReceiver(ActivityThread.java:2431)
                                                                                    at android.app.ActivityThread.access$1500(ActivityThread.java:141)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1332)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                    at android.os.Looper.loop(Looper.java:137)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5103)
                                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:525)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                                    at dalvik.system.NativeStart.main(Native Method)
                                                                                 Caused by: java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
                                                                                    at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:962)
                                                                                    at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:599)
                                                                                    at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
                                                                                    at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
                                                                                    at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:834)
                                                                                    at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
                                                                                    at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:144)
                                                                                    at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
                                                                                    at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
                                                                                    at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:237)
                                                                                    at com.orhanobut.hawk.SqliteStorage$SqliteHelper.get(SqliteStorage.java:170)
                                                                                    at com.orhanobut.hawk.SqliteStorage.get(SqliteStorage.java:38)
                                                                                    at com.orhanobut.hawk.Hawk.get(Hawk.java:115)
                                                                                    at com.orhanobut.hawk.Hawk.get(Hawk.java:148)```

**Comment by orhanobut** [comment]
can you try with the new version? This issue should be fixed. 

1.22

**Comment by PieterAelse** [comment]
Seems legit :+1: thanks!

**Comment by orhanobut** [comment]
perfect, thanks for the feedback. I'm closing the issue.
