### ISSUE TITLE
Serialization problem due to Active Android database library

### ISSUE THREAD

**Issue by ahmadalibaloch** [orhanobut/hawk#147]
The exception looks like this
`Caused by: java.lang.UnsupportedOperationException: Attempted to serialize java.lang.Class: com.dgheating.mobileapp.Entities.Project. Forgot to register a type adapter?`

This happens only when I extend my `Project`class by `com.activeandroid.Model`

Here is the complete exception.

`Caused by: java.lang.UnsupportedOperationException: Attempted to serialize java.lang.Class: com.xx.yy.Entities.Project. Forgot to register a type adapter?
                                                                             at com.google.gson.internal.bind.TypeAdapters$1.write(TypeAdapters.java:69)
                                                                             at com.google.gson.internal.bind.TypeAdapters$1.write(TypeAdapters.java:63)
                                                                             at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
                                                                             at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:113)
                                                                             at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:240)
                                                                             at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
                                                                             at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:113)
                                                                             at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:240)
                                                                             at com.google.gson.internal.bind.ObjectTypeAdapter.write(ObjectTypeAdapter.java:107)
                                                                             at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
                                                                             at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:96)
                                                                             at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:60)
                                                                             at com.google.gson.Gson.toJson(Gson.java:605)
                                                                             at com.google.gson.Gson.toJson(Gson.java:584)
                                                                             at com.google.gson.Gson.toJson(Gson.java:539)
                                                                             at com.google.gson.Gson.toJson(Gson.java:519)
                                                                             at com.orhanobut.hawk.GsonParser.toJson(GsonParser.java:26)
                                                                             at com.orhanobut.hawk.HawkEncoder.encode(HawkEncoder.java:37)
                                                                             at com.orhanobut.hawk.Hawk.zip(Hawk.java:98)
                                                                             at com.orhanobut.hawk.Hawk.put(Hawk.java:57)
                                                                             at com.xx.yy.Fragments.ProjectFragment.gotMyProjects(ProjectFragment.java:84)`

**Comment by orhanobut** [comment]
Is this still an issue with the new version?

**Comment by ahmadalibaloch** [comment]
I am sorry but can't check it as I have moved that app to Realm.
