### ISSUE TITLE
Couldn't open Hawk for writing (will try read-only)

### ISSUE THREAD

**Issue by wangbourne** [orhanobut/hawk#150]
It happen sometimes and I got following error message when I tried to call Hawk.get:

Couldn't open Hawk for writing (will try read-only):
                                                                                       android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14): , while compiling: PRAGMA journal_mode
                                                                                           at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                                           at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
                                                                                           at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:634)
                                                                                           at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:320)
                                                                                           at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:294)
                                                                                           at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
                                                                                           at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
                                                                                           at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
                                                                                           at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
                                                                                           at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
                                                                                           at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:804)
                                                                                           at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:789)
                                                                                           at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
                                                                                           at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:960)
                                                                                           at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:256)
                                                                                           at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:224)
                                                                                           at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:188)
                                                                                           at com.orhanobut.hawk.SqliteStorage$SqliteHelper.get(SqliteStorage.java:156)
                                                                                           at com.orhanobut.hawk.SqliteStorage.get(SqliteStorage.java:40)
                                                                                           at com.orhanobut.hawk.Hawk.get(Hawk.java:100)
                                                                                           at com.orhanobut.hawk.Hawk.get(Hawk.java:128)

**Comment by orhanobut** [comment]
Closing this issue due to new version which doesn't support Sqlite.
