### ISSUE TITLE
Value not persistent after reopening app

### ISSUE THREAD

**Issue by yooneskh** [orhanobut/hawk#87]
Hi.
i have a problem that when i put a value, it is there until i reopen the app. when i do it, Hawk.contains("key") returns true but Hawk.get("key", -1) returns -1.

i use version 1.1 and initialize it with Hawk.init(context).

**Comment by orhanobut** [comment]
Hi, Can you give an example of the value? Could be that it cannot demarshall or could be something else?

**Comment by yooneskh** [comment]
What do you mean by demarshalling?

**Comment by orhanobut** [comment]
values are converted to string by gson and then hawk convert them back to object, in the second step probably something went wrong, do you have inner class in your object? we had some issue and it's been fixed in the newest versions.

**Comment by timaxapa** [comment]
I have the same issue. I try to save User with structure:
 ```java
class User  {
    private long id;
    private String firstName;
    private String lastName;
    private String email;
    private boolean isAdmin;
    private String imageUrl;
    private String birthday;
    private String phone;
    private String position;
}
```
after successfull log in I get null on Hawk.get("user"); at start next activity

**Comment by orhanobut** [comment]
@timaxapa which version are you using?

**Comment by timaxapa** [comment]
@orhanobut 1.19

**Comment by timaxapa** [comment]
@orhanobut Any updates for this issue? Also I try to update to 1.20, but get following error:
```
11-02 12:25:49.530 18643-18643/com.example.app E/AndroidRuntime: FATAL EXCEPTION: main
11-02 12:25:49.530 18643-18643/com.example.app E/AndroidRuntime: Process: com.example.app, PID: 18643
11-02 12:25:49.530 18643-18643/com.example.app E/AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.app/com.example.app.activities.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'byte[] com.orhanobut.hawk.Encryption.decrypt(java.lang.String)' on a null object reference
11-02 12:25:49.530 18643-18643/com.example.app E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
11-02 12:25:49.530 18643-18643/com.example.app E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
11-02 12:25:49.530 18643-18643/com.example.app E/AndroidRuntime:     at android.app.ActivityThread.-wrap11(ActivityThread.java)
11-02 12:25:49.530 18643-18643/com.example.app E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
11-02 12:25:49.530 18643-18643/com.example.app E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
11-02 12:25:49.530 18643-18643/com.example.app E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:148)
11-02 12:25:49.530 18643-18643/com.example.app E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5417)
11-02 12:25:49.530 18643-18643/com.example.app E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
11-02 12:25:49.530 18643-18643/com.example.app E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-02 12:25:49.530 18643-18643/com.example.app E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-02 12:25:49.530 18643-18643/com.example.app E/AndroidRuntime:  Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'byte[] com.orhanobut.hawk.Encryption.decrypt(java.lang.String)' on a null object reference
11-02 12:25:49.530 18643-18643/com.example.app E/AndroidRuntime:     at com.orhanobut.hawk.Hawk.get(Hawk.java:125)
11-02 12:25:49.530 18643-18643/com.example.app E/AndroidRuntime:     at com.example.app.activities.BaseActivity.onCreate(BaseActivity.java:24)
11-02 12:25:49.530 18643-18643/com.example.app E/AndroidRuntime:     at com.example.app.activities.MainActivity.onCreate(MainActivity.java:65)
11-02 12:25:49.530 18643-18643/com.example.app E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:6237)
11-02 12:25:49.530 18643-18643/com.example.app E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
11-02 12:25:49.530 18643-18643/com.example.app E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
11-02 12:25:49.530 18643-18643/com.example.app E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
11-02 12:25:49.530 18643-18643/com.example.app E/AndroidRuntime:     at android.app.ActivityThread.-wrap11(ActivityThread.java) 
11-02 12:25:49.530 18643-18643/com.example.app E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
11-02 12:25:49.530 18643-18643/com.example.app E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
11-02 12:25:49.530 18643-18643/com.example.app E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:148) 
11-02 12:25:49.530 18643-18643/com.example.app E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5417) 
11-02 12:25:49.530 18643-18643/com.example.app E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
11-02 12:25:49.530 18643-18643/com.example.app E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
11-02 12:25:49.530 18643-18643/com.example.app E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

Application class:
```java
Hawk.init(this)
                .setEncryptionMethod(HawkBuilder.EncryptionMethod.MEDIUM)
                .setStorage(HawkBuilder.newSharedPrefStorage(this))
                .setLogLevel(LogLevel.FULL)
                .build();
```

BaseActvity:
```java
user = Hawk.get(HawkUtil.USER);
```

**Comment by timaxapa** [comment]
@orhanobut 
Update: there are no problems without encryption

**Comment by orhanobut** [comment]
Thanks, I was about to ask this question. Could you also tell me which android version and phone or emulator are you trying on?

**Comment by timaxapa** [comment]
Devices:
Nexus 5 - Android 6.0
Nexus 7 - Android 5.1.1

Emulators:
Genymotion Android 5.1
Genymotion Android 4.2.2

**Comment by swapgo20** [comment]
I'm also getting the same issue.

**Comment by orhanobut** [comment]
I'm finally back to spend some time on this. 

@swapgo20 does this happen sometimes or all the time?

**Comment by swapgo20** [comment]
@orhanobut most of the time when app crashes. Now I am trying without encryption.

**Comment by orhanobut** [comment]
Could you give me more details about device, android version, data  and the scenario?

**Comment by orhanobut** [comment]
@timaxapa @swapgo20  do you still have the same issue with the new version? Unfortunately I can't really reproduce this scenario

**Comment by swapgo20** [comment]
We are also not able to reproduce the issue. But, crashlytics reports it most of the time.

**Comment by ilyasdirin** [comment]
I have the same issue, I tried the same data with Hawk and Shared Preferences, after killing and reoppening app,  I'm getting exact data from shared preference on app open, but I'm getting null value (or default) from Hawk.
