### ISSUE TITLE
Strange ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by mblcdr** [orhanobut/hawk#92]
I am receiving some crash logs which I suspect is related to Hawk. Here's the log:

``` Java
java.lang.ArrayIndexOutOfBoundsException: src.length=75 srcPos=0 dst.length=0 dstPos=0 length=57
       at java.lang.System.arraycopy(System.java)
       at java.lang.String.getChars(String.java:889)
       at com.android.internal.util.FastXmlSerializer.append(FastXmlSerializer.java:89)
       at com.android.internal.util.FastXmlSerializer.append(FastXmlSerializer.java:113)
       at com.android.internal.util.FastXmlSerializer.startDocument(FastXmlSerializer.java:326)
       at com.android.internal.util.XmlUtils.writeMapXml(XmlUtils.java:183)
       at android.app.SharedPreferencesImpl.writeToFile(SharedPreferencesImpl.java:598)
       at android.app.SharedPreferencesImpl.access$800(SharedPreferencesImpl.java:52)
       at android.app.SharedPreferencesImpl$2.run(SharedPreferencesImpl.java:513)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:838)
```

In all of the crashes src.length is 75 and length is 57. Maybe it's the salt or some other key that is stored by Hawk? Crashes occurred on devices like: HUAWEI Y320-U30, HUAWEI Y511-U30.
I also can tell that this crashes occurs on the startup of the application.
Any idea why this is happening?

**Comment by orhanobut** [comment]
Thanks for the issue!
Which version of Hawk are you using? It seems that init process is failed somehow. And how do you init Hawk?

**Comment by mblcdr** [comment]
Thank you for responding so fast.
I am using 1.15.  I use the less secure ```Hawk.init(context);``` to initialize hawk.

**Comment by orhanobut** [comment]
It happens only for these devices right? or it happens generally?

**Comment by mblcdr** [comment]
Not generally, lots of devices work fine. There are some other devices, too. However I only mentioned the most common ones.
It also happened only on Android 4.2.2 so far.

**Comment by mblcdr** [comment]
I have more info. Here's another crash, hopefully with line numbers:

```Java
java.lang.ArrayIndexOutOfBoundsException: src.length=75 srcPos=0 dst.length=0 dstPos=0 length=57
       at java.lang.System.arraycopy(System.java)
       at java.lang.String.getChars(String.java:889)
       at com.android.internal.util.FastXmlSerializer.append(FastXmlSerializer.java:89)
       at com.android.internal.util.FastXmlSerializer.append(FastXmlSerializer.java:113)
       at com.android.internal.util.FastXmlSerializer.startDocument(FastXmlSerializer.java:326)
       at com.android.internal.util.XmlUtils.writeMapXml(XmlUtils.java:183)
       at android.app.SharedPreferencesImpl.writeToFile(SharedPreferencesImpl.java:598)
       at android.app.SharedPreferencesImpl.access$800(SharedPreferencesImpl.java:52)
       at android.app.SharedPreferencesImpl$2.run(SharedPreferencesImpl.java:513)
       at android.app.SharedPreferencesImpl.enqueueDiskWrite(SharedPreferencesImpl.java:534)
       at android.app.SharedPreferencesImpl.access$100(SharedPreferencesImpl.java:52)
       at android.app.SharedPreferencesImpl$EditorImpl.commit(SharedPreferencesImpl.java:456)
       at com.c.a.x.a(SharedPreferencesStorage.java:22)
       at com.c.a.n.a(Hawk.java:176)
       at com.example.app.a.a.a(AppConfig.java:92)
       at com.example.app.service.LocationService.onLocationChanged(LocationService.java:261)
       at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:257)
       at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:186)
       at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:202)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5371)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

in ```AppConfig.java line 92``` I have:

```Java
Hawk.put("lastLocation", l);
```
in which ```l``` is a simple class.

**Comment by orhanobut** [comment]
This issue seems very specific, hopefully within this week I can recreate the same error.

**Comment by mblcdr** [comment]
Good to know. Let me know if you need any more info.

**Comment by prashantpandeyfun10** [comment]
Was there any luck with this error @orhanobut

**Comment by mblcdr** [comment]
I think this is not related to Hawk. On some devices there is a problem with SharedPreferences that causes this. So nothing we can do here I suppose. Feel free to close. @orhanobut

**Comment by MaYinjian** [comment]
Yes. It happenes all in  android  api 17  . I got about 100 crash since the beginning of time.

**Comment by orhanobut** [comment]
Closing this one since author mentioned that it's not related to Hawk.
