### ISSUE TITLE
Hawk should allow broken PRNG or at least fallback

### ISSUE THREAD

**Issue by mblcdr** [orhanobut/hawk#93]
On some devices with old updates, PRNG is broken, causing crashes. For example Nokia XL with Android 4.1. In latest updates to `AesCbcWithIntegrity` this flag is introduced:

``` Java
private static final boolean ALLOW_BROKEN_PRNG = false;
```

which if set to true will prevent SecurityException on such devices in places like:

``` Java
if (!rng2.getProvider().getClass().getSimpleName().equals("LinuxPRNGSecureRandomProvider")) {
    if (ALLOW_BROKEN_PRNG) {
            Log.w(PrngFixes.class.getSimpleName(),
                    "SecureRandom.getInstance(\"SHA1PRNG\") backed by wrong" + " Provider: "
                    + rng2.getProvider().getClass());
            return;
    } else {
            throw new SecurityException(
                "SecureRandom.getInstance(\"SHA1PRNG\") backed by wrong" + " Provider: "
                + rng2.getProvider().getClass());
    }
}
```

Without that on some devices crashes like this will occur as stated above:

``` Java
java.lang.SecurityException: SecureRandom.getInstance("SHA1PRNG") backed by wrong Provider: class org.apache.harmony.security.provider.crypto.CryptoProvider
       at com.c.a.c.d(AesCbcWithIntegrity.java:718)
       at com.c.a.c.a(AesCbcWithIntegrity.java:642)
       at com.c.a.a.d(AesCbcWithIntegrity.java:313)
       at com.c.a.a.a(AesCbcWithIntegrity.java:219)
       at com.c.a.a.c(AesCbcWithIntegrity.java:215)
       at com.c.a.a.a(AesCbcWithIntegrity.java:289)
       at com.c.a.g.a(AesEncryption.java:45)
       at com.c.a.n.b(Hawk.java:218)
       at com.c.a.n.a(Hawk.java:174)
       ...
```

I think as an encrypted storage library, Hawk should allow broken PRNG. I also don't see why Hawk is not using the latest version of `AesCbcWithIntegrity`. Are there any conflicts?
I suggest updating to the latest `AesCbcWithIntegrity` and setting that flag to true.
I can send a pull request with these changes if that's ok. Just let me know.

**Comment by orhanobut** [comment]
Thanks for this good feedback,definitely I'll appreciate PR for this change. That would be great if you can write test to cover this situation in order to make sure everything works well.

**Comment by scottyab** [comment]
Check out the PR I just raised for java-aes-crypto that fixes this 'backed by wrong Provider'  issue.   https://github.com/tozny/java-aes-crypto/pull/18

**Comment by orhanobut** [comment]
@scottyab  thanks! I still use the copy-paste file and changed the class a little bit regarding to my needs, but I would like to use it as dependency since I see there are fixes and changes going on.

**Comment by scottyab** [comment]
I'm maintaining my own fork of java-aes-crypto that is also published to maven central. Feel free to use it `compile 'com.scottyab:aes-crypto:0.0.4'`

**Comment by orhanobut** [comment]
:+1:

**Comment by mblcdr** [comment]
@scottyab Thanks for the effort. While you are working on it, I would like to mention one other problem which is caused by SHA1PRNG not being available on the device at all. This will happen as soon as a request to put something is issued to Hawk. And so a stack trace such as the one below occurs:

```Java
java.lang.SecurityException: SHA1PRNG not available
       at com.c.a.c.d(AesCbcWithIntegrity.java:715)
       at com.c.a.c.a(AesCbcWithIntegrity.java:642)
       at com.c.a.a.d(AesCbcWithIntegrity.java:313)
       at com.c.a.a.a(AesCbcWithIntegrity.java:219)
       at com.c.a.a.c(AesCbcWithIntegrity.java:215)
       at com.c.a.a.a(AesCbcWithIntegrity.java:289)
       at com.c.a.g.a(AesEncryption.java:45)
       at com.c.a.n.b(Hawk.java:218)
       at com.c.a.n.a(Hawk.java:174)
       at com.nazdika.app.a.a.a(AppConfig.java:92)
       at com.nazdika.app.service.LocationService.onLocationChanged(LocationService.java:261)
       at com.google.android.gms.location.internal.t.handleMessage()
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4424)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.security.NoSuchAlgorithmException: SecureRandom SHA1PRNG implementation not found
       at org.apache.harmony.security.fortress.Engine.notFound(Engine.java:177)
       at org.apache.harmony.security.fortress.Engine.getInstance(Engine.java:151)
       at java.security.SecureRandom.getInstance(SecureRandom.java:159)
       at com.c.a.c.d(AesCbcWithIntegrity.java:713)
       at com.c.a.c.a(AesCbcWithIntegrity.java:642)
       at com.c.a.a.d(AesCbcWithIntegrity.java:313)
       at com.c.a.a.a(AesCbcWithIntegrity.java:219)
       at com.c.a.a.c(AesCbcWithIntegrity.java:215)
       at com.c.a.a.a(AesCbcWithIntegrity.java:289)
       at com.c.a.g.a(AesEncryption.java:45)
       at com.c.a.n.b(Hawk.java:218)
       at com.c.a.n.a(Hawk.java:174)
       at com.nazdika.app.a.a.a(AppConfig.java:92)
       at com.nazdika.app.service.LocationService.onLocationChanged(LocationService.java:261)
       at com.google.android.gms.location.internal.t.handleMessage()
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4424)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

Maybe Hawk should catch this and act accordingly (maybe fall back to no-crypto, or use other algorithms?) or simply can ignore it?
This is also ignored if ```ALLOW_BROKEN_PRNG``` is set to true, but I don't know what will happen in Hawk if such an exception is ignored. Here's the code which I am referring to:

```Java
try {
    rng2 = SecureRandom.getInstance("SHA1PRNG");
} catch (NoSuchAlgorithmException e) {
    if (ALLOW_BROKEN_PRNG) {
        Log.w(PrngFixes.class.getSimpleName(), "SHA1PRNG not available", e);
        return;
    } else {
        new SecurityException("SHA1PRNG not available", e);
    }
}
```

**Comment by Methe** [comment]
I had this problem on my project too!

The problem was in my build.gralde file. The flag minifyEnabled was enabled, and when gradle builds the project, probably it was removing some necessary methods/classes.

Adding that line on my proguard-rules.pro solved my problem:

`-keep class com.orhanobut.hawk.AesCbcWithIntegrity$PrngFixes$LinuxPRNGSecureRandom { *; }
`

**Comment by orhanobut** [comment]
Closing this one for now.
